#!/usr/bin/env bash

function elastic_alias_help() {
  cat << EOF
Usage:
  elastic [<options>] alias <subcommand> [<args>]

Alias management
  alias list                              Lists all index aliases
  alias get [<alias>]                     Returns information about one or more index aliases
  alias add <alias> <index> [<body>]      Creates or updates an index alias
  alias delete <alias> <index>            Deletes an existing index alias
  alias switch <alias> <from> <to>        Moves an alias from one index to another

Examples:
  elastic alias add my-alias my-index
  elastic alias switch my-alias old-index new-index
EOF
}

function elastic_alias() {
  if [ $# -eq 0 ]; then
    SUBCMD="list"
  else
    SUBCMD="$1"; shift
  fi

  FUNC="elastic_alias_${SUBCMD}"
  run_func $FUNC "$@"
}

function elastic_alias_list() {
  get _cat/aliases
}

function elastic_alias_get() {
  ALIAS="$1"
  get _alias/$ALIAS
}

function elastic_alias_add() {
  ALIAS="$1"; assert "$ALIAS" "missing alias argument"
  INDEX="$2"; assert "$INDEX" "missing index argument"
  BODY="$3"

  if [ -z "$BODY" ]; then
    put $INDEX/_alias/$ALIAS
  else
    put $INDEX/_alias/$ALIAS --data "$BODY"
  fi
}

function elastic_alias_delete() {
  ALIAS="$1"; assert "$ALIAS" "missing alias argument"
  INDEX="$2"; assert "$INDEX" "missing index argument"
  delete $INDEX/_alias/$ALIAS
}

function elastic_alias_switch() {
  ALIAS="$1"; assert "$ALIAS" "missing alias argument"
  FROM="$2"; assert "$FROM" "missing from argument"
  TO="$3"; assert "$TO" "missing to argument"

  BODY=$(cat <<JSON
{
  "actions": [
    { "add": { "index": "${TO}", "alias": "${ALIAS}" } },
    { "remove": { "index": "${FROM}", "alias": "${ALIAS}" } }
  ]
}
JSON
)

  post _aliases --data "$BODY"
}
