#!/usr/bin/env bash

function elastic_curl_help() {
  cat << EOF
Usage:
  elastic [<options>] curl <subcommand> [<args>]

Arbitrary HTTP requests
  curl get <path> [<curl args>]           Makes arbitrary GET request
  curl post <path> [<curl args>]          Makes arbitrary POST request
  curl put <path> [<curl args>]           Makes arbitrary PUT request
  curl delete <path> [<curl args>]        Makes arbitrary DELETE request

Examples:
  elastic --cluster http://mycluster:9200 curl post my-index/_search -H "Authorization: ..." -d '{"query": {...}}'
EOF
}

function elastic_curl() {
  SUBCMD="$1"; assert "$SUBCMD" "missing subcommand"; shift
  FUNC="elastic_curl_${SUBCMD}"
  run_func $FUNC "$@"
}

function elastic_curl_get() {
  get "$@"
}

function elastic_curl_post() {
  post "$@"
}

function elastic_curl_put() {
  put "$@"
}

function elastic_curl_delete() {
  delete "$@"
}
