#!/usr/bin/env bash

function elastic_search_help() {
  cat << EOF
Usage:
  elastic [<options>] search <index> [<query>]

Search API
  search <index> [<body>]                 Returns search hits that match the query defined in the request

Examples:
  elastic search my-index/ '{"query": {...}}'
EOF
}

function elastic_search() {
  INDEX="$1"; assert "$INDEX" "missing index argument"
  QUERY="$2"

  if [ -z "$QUERY" ]; then
    post $INDEX/_search
  else
    post $INDEX/_search --data "$QUERY"
  fi
}
