#!/usr/bin/env bash

function load_cmd() {
  CMD="$1"; shift
  CMD_PATH="$ELASTIC_ROOT/src/commands/$CMD"

  if [ -f $CMD_PATH ]; then
    source $CMD_PATH
  else
    echo "elastic: '$CMD' is not a command. See 'elastic help'."
    exit 1
  fi
}

function run_cmd() {
  CMD="$1"; shift
  load_cmd $CMD
  run_func "elastic_${CMD}" "$@"
}

function run_func() {
  FUNC="$1"; shift
  EXISTS=$(type $FUNC >/dev/null 2>/dev/null && echo "yes" || echo "no" )

  if [ "$EXISTS" == "yes" ]; then
    $FUNC "$@"
  else
    echo "'$(echo $FUNC | sed 's/_/ /g')' is not a command. See 'elastic index help'."
  fi
}

function assert() {
  [[ -z "$1" ]] && echo $2 1>&2 && exit 1 || true
}

function maybe_verbose() {
  if [[ $VERBOSE = "1" ]]; then
    (set -x; "$@")
  else
    "$@"
  fi
}

function get() {
  maybe_verbose $CURL "$CLUSTER/$1"
}

function post() {
  maybe_verbose $CURL -X POST -H "Content-Type: application/json" $CLUSTER/"$@"
}

function put() {
  maybe_verbose $CURL -X PUT -H "Content-Type: application/json" $CLUSTER/"$@"
}

function delete() {
  maybe_verbose $CURL -X DELETE $CLUSTER/"$@"
}
